### PR TITLE
[RDY] mouse ctx menu

### PR DESCRIPTION
**Pull request by yatli**
@RamonUnch FYI this is a sketch of a feature I call "mouse context menu".
It allows one to not designate an exact action to a mouse button, but instead, show a popup of available actions (e.g. borderless, alwaysontop)

### CODE REVIEW

**Comment by yatli** [comment]
There's a lag when the popup menu is opened before an action can be selected. No idea what's happening here.
Also, alwaysontop isn't 100% working -- when enabled, the context menu would not reliably show over the pinned window 😂

**Comment by RamonUnch** [comment]
Cool I was thinking about adding this feature myself but always pushed it away.
In this case, I think it would be good to also add the close action in the popup menu.

You are using the timer window proc, I think this may be the issue, just create a new one and destroy it once the menu action is done.

**Comment by yatli** [comment]
Got it. Will try this after some sleep :p

**Comment by RamonUnch** [comment]
I think you could also use the 
TPM_NONOTIFY  |  TPM_RETURNCMD flags for the TrackPopupMenu function hence avoiding to use messages but instead using the result value of TrackPopupMenu on site. 
This would also avoid adding a global variable.
good night.

**Comment by RamonUnch** [comment]
After further thinking, I think that it would be beter to just post a message to the cursorwnd (that is handeled by AltDrag.exe) and to handle the menu cration and actions in the `altdrag.c::WindowProc`.
We should create a `sclick_actions` function that is exported by `hooks.dll` and that would contail all the sigle clic actions that could be relevant on the menu and could be called in the `WindowProc` as well as in` init_movement_and_actions` (to avoid code duplication). This would also allow for translations of the menu items (just would have to use `l10n->input_actions_borderless`) where it is allocated. Otherwise if we start to put GUI in hooks.dll all the language code and strings will have to be loaded twice.
If you keep it very simple however it can remain in hooks.dll and be improved later on.

**Comment by yatli** [comment]
Got it. So `void Load(void)` should become `HWND Load(HWND)` right?

**Comment by yatli** [comment]
The lag is gone after moving the logic out of timer proc.

**Comment by yatli** [comment]
67bfcd4

**Comment by yatli** [comment]
I'm quite happy with this version now. Ready for review.

**Comment by RamonUnch** [comment]
Seems prety good, I will see more in details this evening.

**Comment by RamonUnch** [comment]
I just tried blindly and it seems that the menu pops down instantly when using Alt as a hotkey (works with Winkey fine)

**Comment by yatli** [comment]
> I just tried blindly and it seems that the menu pops down instantly when using Alt as a hotkey (works with Winkey fine)

Yeah it's tricky. To catch it, release alt key before moving mouse.

**Comment by RamonUnch** [comment]
The problem you have is that if you hit Alt down then it kills the menu, there must be a message that can be processed in the menu winproc to avoid this, it ir really unusable if you use alt with a short auto-repeat delay set in your keyboard.

**Comment by yatli** [comment]
Thanks. I think I understand the cause now.
Plus that keyboard accelerators for the menu would be pretty cool. `Alt+MMB c` is no harder than first aiming at the taskbar, then `shift+RMB c`

**Comment by RamonUnch** [comment]
Grabted that in a menu you do not need to press alt to have the accelerators.
You do not need actually to return a value from Load() because you can pass the g_mchwnd as wParam in your PostMessage.
You also do not need to pass the mainhwnd as a parameter because it is also the cursorwnd.
Maybe it is beter to rename cursorwnd g_mainhwnd and pass it as a parameter of Load like you do.
those are just details I can arrange myself, do not worry about it.

**Comment by RamonUnch** [comment]
I tried to ignore WM_SYSKEYDOWN events in the menuwindowproc but without sucess, so I just modified the LowLevelKeyboardHook to bloc alt keydown events when the state.sclickhwnd is non null.
Also why do you use SC_ACTION+action, this is the wParam there should be no need to do this, because the WM_SCLICK message is already resrved. Maybe you have a reason?

**Comment by yatli** [comment]
About `WM_SYSKEYDOWN`, I translated the messages hitting the proc:

```
GOOD:

SClickWindowProc: msg=WM_IME_SETCONTEXT
SClickWindowProc: msg=WM_IME_NOTIFY
SClickWindowProc: msg=WM_SETFOCUS
SClickWindowProc: msg=WM_ENTERMENULOOP
SClickWindowProc: msg=(null)
SClickWindowProc: msg=WM_INITMENU
SClickWindowProc: msg=WM_INITMENUPOPUP
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
ModLoad: 6f810000 6f8a4000   C:\WINDOWS\SysWOW64\TextShaping.dll
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_ENTERIDLE
```

```
BAD:

SClickWindowProc: msg=WM_ENTERMENULOOP
SClickWindowProc: msg=(null)
SClickWindowProc: msg=WM_INITMENU
SClickWindowProc: msg=WM_INITMENUPOPUP
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=(null)
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_ENTERIDLE
SClickWindowProc: msg=WM_CAPTURECHANGED
SClickWindowProc: msg=WM_UNINITMENUPOPUP <-------------------------- this is before WM_SYSKEYDOWN
SClickWindowProc: msg=WM_MENUSELECT
SClickWindowProc: msg=WM_EXITMENULOOP
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_SYSKEYDOWN
SClickWindowProc: msg=WM_KEYDOWN
SClickWindowProc: msg=WM_SYSKEYUP
SClickWindowProc: msg=WM_KEYUP
```

**Comment by RamonUnch** [comment]
Yep I came to the same conclusion, this is why I used 

```
        } else if (state.sclickhwnd && state.alt && (vkey == VK_LMENU || vkey == VK_RMENU)) {
            return 1;
        }
```
At the end of the     `if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {` branch of the `LowLevelKeyboardProc`
And it works.
I will merge your pull request and make the extra modif myself, I already did them, so do not worry.

**Comment by yatli** [comment]
Thanks!

> In a menu you do not need to press alt to have the accelerators.

Yeah, I just thought it'd make sense to watch for WM_KEYDOWN and implement the accelerator manually.
Could also be done in altdrag.c, some strcat required.

**Comment by RamonUnch** [comment]
I am hesitant to use strcat to append accelerators, i think it is simpler to add them to the language.h and teanslations strings because for people using a russian greek KB this would be annoying to force ascii key.
For the droplist (that does not like to have the '&', I would strip them out.

**Comment by yatli** [comment]
Got it.

>  Also why do you use SC_ACTION+action, this is the wParam there should be no need to do this, because the WM_SCLICK message is already resrved. Maybe you have a reason?

```
hook --[WM_SCLICK]-->altdrag          fine
altdrag --[WM_COMMAND]-->hook  maybe a problem, so offset with SC_ACTION
```

**Comment by RamonUnch** [comment]
>altdrag --[WM_COMMAND]-->hook  maybe a problem, so offset with SC_ACTION
Yes but in the WM_COMMAND case only our code should be executedin this sclicmenuwindow.
From the DOC MS specifies that the space WM_APP is reserved for the application in the case of the message, nothing is specified about the *Params.

**Comment by yatli** [comment]
Ah ok. So we can safely assume WM_COMMAND uses user-defined wParam.

**Comment by yatli** [comment]
5002ea9 could you help to double check this? Brain's not working now -- need to sleep.

**Comment by RamonUnch** [comment]
I already modified this function indeed threr were some problems.
you defined state.sclickhwnd but were still using state.hwnd.
I made an other function that is called by this proc and is also called by the init_movement_and_actions function. it is all fine, I will merge your PR and my modifications on top of it.

**Comment by RamonUnch** [comment]
Good night

**Comment by RamonUnch** [comment]
I love this action, it will be my new default for MMB...
Thanks

**Pull request merged**
